# This test code was written by the `hypothesis.extra.ghostwriter` module
# and is provided under the Creative Commons Zero public domain dedication.
#
# Generated by:
#   uv run --with 'hypothesis[cli]' hypothesis write --style=pytest \
#       orderbooks.viz.bitmap_occupancy
#
# The strategy is narrowed to logs that hold a top event, which render
# requires.

from hypothesis import given
from hypothesis import strategies as st

import orderbooks.viz.bitmap_occupancy
from orderbooks.viz.event_log import EventLog


@given(
    log=st.from_type(EventLog).filter(lambda log: not log.tops.empty),
    px_bins=st.just(80),
    bins=st.just(200),
    output=st.none(),
)
def test_fuzz_render(log: EventLog, px_bins: int, bins: int, output: None) -> None:
    orderbooks.viz.bitmap_occupancy.render(
        log=log, px_bins=px_bins, bins=bins, output=output
    )
