# This test code was written by the `hypothesis.extra.ghostwriter` module
# and is provided under the Creative Commons Zero public domain dedication.
#
# Generated by:
#   uv run --with 'hypothesis[cli]' hypothesis write --style=pytest \
#       orderbooks.viz.depth
#
# The strategies are narrowed to the engine's field widths, which conftest
# registers, and to logs that hold a top event, which at_seq requires.

from hypothesis import given
from hypothesis import strategies as st

import orderbooks.viz.depth
from orderbooks.viz.depth import BookSnapshot
from orderbooks.viz.event_log import EventLog


@given(snapshot=st.from_type(BookSnapshot))
def test_fuzz_BookSnapshot(snapshot: BookSnapshot) -> None:
    orderbooks.viz.depth.BookSnapshot(
        seq=snapshot.seq,
        bid_px=snapshot.bid_px,
        ask_px=snapshot.ask_px,
        bid_qty=snapshot.bid_qty,
        ask_qty=snapshot.ask_qty,
    )


@given(
    log=st.from_type(EventLog).filter(lambda log: not log.tops.empty),
    seq=st.from_type(BookSnapshot).map(lambda snapshot: snapshot.seq),
)
def test_fuzz_at_seq(log: EventLog, seq: int) -> None:
    orderbooks.viz.depth.at_seq(log=log, seq=seq)


@given(snapshot=st.from_type(BookSnapshot), output=st.none())
def test_fuzz_render(snapshot: BookSnapshot, output: None) -> None:
    orderbooks.viz.depth.render(snapshot=snapshot, output=output)
