# This test code was written by the `hypothesis.extra.ghostwriter` module
# and is provided under the Creative Commons Zero public domain dedication.
#
# Generated by:
#   uv run --with 'hypothesis[cli]' hypothesis write --style=pytest \
#       orderbooks.viz.event_log
#
# The strategies are narrowed to the stream json_recorder writes, which
# conftest registers and reads through read_file. The missing-field case is
# written by hand, since no generated stream lacks a field.

from pathlib import Path

import pytest
from hypothesis import given
from hypothesis import strategies as st

import orderbooks.viz.event_log
from orderbooks.viz.event_log import EventLog, MissingFieldError, read_file


@given(log=st.from_type(EventLog))
def test_fuzz_EventLog(log: EventLog) -> None:
    orderbooks.viz.event_log.EventLog(
        fills=log.fills,
        tops=log.tops,
        trades=log.trades,
        self_trades=log.self_trades,
        rejects=log.rejects,
    )


def test_read_file_rejects_missing_field(tmp_path: Path) -> None:
    path = tmp_path / "events.jsonl"
    path.write_text('{"kind":"fill","maker":1,"px":5,"qty":3,"seq":1}\n')
    with pytest.raises(MissingFieldError):
        read_file(path)
