# This test code was written by the `hypothesis.extra.ghostwriter` module
# and is provided under the Creative Commons Zero public domain dedication.
#
# Generated by:
#   uv run --with 'hypothesis[cli]' hypothesis write --style=pytest \
#       orderbooks.viz.top_series
#
# The strategy is narrowed to logs that hold a top event, which render
# requires.

from hypothesis import given
from hypothesis import strategies as st

import orderbooks.viz.top_series
from orderbooks.viz.event_log import EventLog


@given(
    log=st.from_type(EventLog).filter(lambda log: not log.tops.empty), output=st.none()
)
def test_fuzz_render(log: EventLog, output: None) -> None:
    orderbooks.viz.top_series.render(log=log, output=output)
