# This test code was written by the `hypothesis.extra.ghostwriter` module
# and is provided under the Creative Commons Zero public domain dedication.
#
# Generated by:
#   uv run --with 'hypothesis[cli]' hypothesis write --style=pytest \
#       orderbooks.viz.flow_heatmap
#
# The strategy is narrowed to logs that hold a fill event, which render
# requires.

from hypothesis import given
from hypothesis import strategies as st

import orderbooks.viz.flow_heatmap
from orderbooks.viz.event_log import EventLog


@given(
    log=st.from_type(EventLog).filter(lambda log: not log.fills.empty),
    px_bins=st.just(80),
    time_bins=st.just(120),
    output=st.none(),
)
def test_fuzz_render(log: EventLog, px_bins: int, time_bins: int, output: None) -> None:
    orderbooks.viz.flow_heatmap.render(
        log=log, px_bins=px_bins, time_bins=time_bins, output=output
    )
