# This test code was written by the `hypothesis.extra.ghostwriter` module
# and is provided under the Creative Commons Zero public domain dedication.
#
# Generated by:
#   uv run --with 'hypothesis[cli]' hypothesis write --style=pytest \
#       orderbooks.viz.event_log
#
# The strategies are narrowed to the stream json_recorder writes, which
# conftest registers and reads through read_file. read_file is left out,
# since it reads a path from disk and every EventLog drawn here passes
# through it.

from hypothesis import given
from hypothesis import strategies as st

import orderbooks.viz.event_log
from orderbooks.viz.event_log import EventLog


@given(log=st.from_type(EventLog))
def test_fuzz_EventLog(log: EventLog) -> None:
    orderbooks.viz.event_log.EventLog(
        fills=log.fills,
        tops=log.tops,
        trades=log.trades,
        self_trades=log.self_trades,
        rejects=log.rejects,
    )


@given(kind=st.text())
def test_fuzz_MissingFieldError(kind: str) -> None:
    orderbooks.viz.event_log.MissingFieldError(kind=kind)
