# cmake-lint: disable=C0103
include_guard(GLOBAL)
include(CheckCXXCompilerFlag)

add_library(lob_compiler_flags INTERFACE)
add_library(lob::compiler_flags ALIAS lob_compiler_flags)

target_compile_features(lob_compiler_flags INTERFACE cxx_std_20)

# Probe each candidate flag with -Werror so that compilers which accept the flag with a warning
# (e.g. Apple Clang on -fno-semantic-interposition) are correctly detected as "unsupported".
function(_lob_probe_flag flag out_var)
  set(_old "${CMAKE_REQUIRED_FLAGS}")
  set(CMAKE_REQUIRED_FLAGS "${flag} -Werror")
  string(MAKE_C_IDENTIFIER "LOB_HAVE_CXX_${flag}" _id)
  check_cxx_compiler_flag("${flag}" ${_id})
  set(CMAKE_REQUIRED_FLAGS "${_old}")
  set(${out_var}
      "${${_id}}"
      PARENT_SCOPE)
endfunction()

if(MSVC)
  target_compile_options(lob_compiler_flags INTERFACE /permissive- /Zc:__cplusplus /Zc:preprocessor
                                                      /utf-8)
else()
  target_compile_options(
    lob_compiler_flags INTERFACE -fno-omit-frame-pointer -fdiagnostics-color=always
                                 -fvisibility=hidden -fvisibility-inlines-hidden)

  if(CMAKE_BUILD_TYPE STREQUAL "Release" OR CMAKE_BUILD_TYPE STREQUAL "RelWithDebInfo")
    # -fno-trapping-math and -ffp-contract=fast both relax floating-point semantics. The engine
    # itself is integer-only today, but any future FP analytics translation unit linked under these
    # flags will have FMA contraction permitted and trapping ops removed; rounding may differ from a
    # strict-IEEE build. Re-evaluate before adding any production FP risk path.
    set(_lob_perf_candidates
        -fno-plt
        -fno-semantic-interposition
        -fstrict-aliasing
        -falign-functions=64
        -falign-loops=32
        -fno-trapping-math
        -ffp-contract=fast)
    set(_lob_perf_compile "")
    foreach(_flag IN LISTS _lob_perf_candidates)
      _lob_probe_flag("${_flag}" _ok)
      if(_ok)
        list(APPEND _lob_perf_compile "${_flag}")
      endif()
    endforeach()
    target_compile_options(lob_compiler_flags INTERFACE ${_lob_perf_compile})
  endif()
endif()

if(LOB_ENABLE_NATIVE AND NOT MSVC)
  target_compile_options(lob_compiler_flags INTERFACE -march=native -mtune=native)
elseif(NOT MSVC AND CMAKE_SYSTEM_PROCESSOR MATCHES "x86_64|AMD64")
  target_compile_options(lob_compiler_flags INTERFACE -march=x86-64-v3)
endif()

# Profile-guided optimisation. Two passes, and the profile is generated by the engine's own
# workloads rather than described here:
#
# just pgo-train     # instrumented build, runs every lob_profile workload, # merges the raw counts
# into artifacts/pgo/train.profdata just pgo-build     # release build that reads it
#
# Counted with cachegrind over the profiler's workloads, the profile is worth between 0.5 and 2.5
# per cent of instructions retired (ADR-0051), with the cache miss counts unchanged, which is what a
# layout and inlining change should look like. It is off by default because a stale profile silently
# pessimises, and the file is a build input that has to be regenerated when the hot paths move.
if(LOB_PGO STREQUAL "generate")
  if(MSVC)
    message(WARNING "LOB_PGO ignored on MSVC")
  else()
    target_compile_options(lob_compiler_flags INTERFACE -fprofile-instr-generate)
    target_link_options(lob_compiler_flags INTERFACE -fprofile-instr-generate)
  endif()
elseif(LOB_PGO STREQUAL "use")
  if(NOT EXISTS "${LOB_PGO_PROFILE}")
    message(FATAL_ERROR "LOB_PGO=use needs LOB_PGO_PROFILE to name a .profdata file; "
                        "run `just pgo-train` first")
  endif()
  target_compile_options(lob_compiler_flags INTERFACE "-fprofile-instr-use=${LOB_PGO_PROFILE}")
  target_link_options(lob_compiler_flags INTERFACE "-fprofile-instr-use=${LOB_PGO_PROFILE}")
  # The training set is the engine's own workloads, so the gateway, the replay tool and the
  # generated version file are legitimately unprofiled; under -Werror that diagnostic would fail the
  # build for doing what was intended. A profile that disagrees with a function it does know is
  # different: it means the profile has aged past the code, so that one stays a warning and is only
  # demoted from an error.
  if(NOT MSVC)
    target_compile_options(lob_compiler_flags INTERFACE -Wno-profile-instr-unprofiled
                                                        -Wno-error=profile-instr-out-of-date)
  endif()
elseif(NOT LOB_PGO STREQUAL "off")
  message(FATAL_ERROR "LOB_PGO must be off, generate or use")
endif()

# Source-based coverage instrumentation, which llvm-cov reads to report which regions, lines and
# branches a run reached. Used by `just coverage` over the test suite and by `just coverage-fuzz` to
# replay the fuzz corpora, which is how the parser's real coverage is measured: the corpora reach
# parts of it no unit test does.
if(LOB_COVERAGE)
  if(MSVC)
    message(WARNING "LOB_COVERAGE ignored on MSVC")
  else()
    target_compile_options(lob_compiler_flags INTERFACE -fprofile-instr-generate -fcoverage-mapping)
    target_link_options(lob_compiler_flags INTERFACE -fprofile-instr-generate -fcoverage-mapping)
  endif()
endif()
