# Compile every public header on its own.
#
# A header-only library is reached only through whatever happens to include it, so two things go
# unchecked: whether a header compiles without a particular include order in front of it, and
# whether the analysers ever see it at all. clang-tidy works from the compilation database, and a
# header that no translation unit includes directly is not in it.
#
# This generates one translation unit per header, from the directory rather than from a list, and
# compiles them as an object library. The headers are then self-contained by construction, they
# carry the project's warning set, and they appear in the compilation database, so `just lint`
# covers them with no separate pass and nothing to keep in step.
include_guard(GLOBAL)

# Adds an object library that compiles each public header on its own.
#
# The translation units are generated from the contents of include/lob, so a header added to the
# directory is covered without this file being edited.
#
# target: name of the object library to create.
function(lob_add_header_self_containment_target target)
  file(GLOB _lob_headers CONFIGURE_DEPENDS "${PROJECT_SOURCE_DIR}/include/lob/*.hpp")
  list(SORT _lob_headers)

  set(_lob_header_tus "")
  foreach(_header IN LISTS _lob_headers)
    get_filename_component(_name "${_header}" NAME_WE)
    set(_tu "${CMAKE_CURRENT_BINARY_DIR}/header_tus/${_name}.cpp")
    # file(GENERATE) rewrites only when the content changes, so these do not rebuild on every
    # configure.
    file(
      GENERATE
      OUTPUT "${_tu}"
      CONTENT
        "// Generated by cmake/HeaderSelfContainment.cmake: compiles
// <lob/${_name}.hpp> on its own, so the header is self-contained and the
// analysers can see it through the compilation database.
#include <lob/${_name}.hpp>
")
    list(APPEND _lob_header_tus "${_tu}")
  endforeach()

  add_library(${target} OBJECT ${_lob_header_tus})
  target_link_libraries(${target} PRIVATE lob::core lob::compiler_flags lob::warnings
                                          lob::hardening)
endfunction()
